### ISSUE TITLE
This is only a "go run" of authority

### ISSUE THREAD

**Issue by baiyunping333** [sbinet/go-eval#15]
This is only a "go run" of authority simply，why a project for that?

**Comment by sbinet** [comment]
an interpreter (`go-eval`) and an on-the-fly-compiler (`go run`) are 2 different things, with their own merits and use cases.

mainly, with an interpreter, you can fiddle with the current state of a program, adding new functions/types w/o recompiling+re-running from the top.

**Comment by sbinet** [comment]
feel free to re-open if something isn't clear.
