### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by cosmos72** [sbinet/go-eval#18]
Hello,

is there activity on go-eval or on the new SSA interpreter https://github.com/go-interpreter/ssainterp ?
They both they seem nice but work-in-progress, i.e. many features are not yet implemented.

I wrote my own Go interpreter https://github.com/cosmos72/gomacro before learning about these, and it's now fairly complete, so I have mixed feelings about the duplication... on one side it shows me there are other people interested in a Go interpreter, and a possibility for cooperation, on the other it could be constructed as "yet another reimplementation"

Best regards,

cosmos72

**Comment by sbinet** [comment]
@cosmos72 go-eval is dormant.
nowadays, the work is poured into go-interpreter:
 https://github.com/go-interpreter/proposal/issues/1

I've also sent a GSoC proposal for this year:
 http://hepsoftwarefoundation.org/gsoc/proposal_GoInterpreterWagon.html
and got a few prospective students.
we'll see (very soon) whether "wagon" managed to get a GSoC slot...

I've also created a #go-interpreter channel on the gophers' slack.
and a mailing list: https://groups.google.com/forum/#!forum/go-interpreter

feel free to say hi on one of these media and talk about interpreters :)

**Comment by cosmos72** [comment]
Thanks :)
I subscribed to the mailing list
