### ISSUE TITLE
when to complete imports can i run it likes python eval,How to import functions, how to interact with the code outside the string,How to use the REPL mode in the Golang language

### ISSUE THREAD

**Issue by ghost** [sbinet/go-eval#19]
when to complete imports can i run it likes python eval Inside the code,Is there a code example?How to import functions, how to interact with the code outside the string

**Comment by ghost** [comment]
how to eval string like python eval which can interact code outside of string on golang,is there a code example?

**Comment by ghost** [comment]
How to use the REPL mode in the Golang language

**Comment by sbinet** [comment]
Same answer than on sbinet/igo.
Please use gomacro or yaegi
